### ISSUE TITLE
Área de materiais de estudo está com links quebrados

### ISSUE THREAD

**Issue by professorsoares** [androiddevbr/materiais-de-estudo#17]
Os links que usam o bit.do não estão funcionando...

https://github.com/androiddevbr/materiais-de-estudo

**Comment by walmyrcarvalho** [comment]
@professorsoares Obrigado pela mensagem, Soares! Vou fazer um PR ajustando os links quebrados! :)

**Comment by walmyrcarvalho** [comment]
@professorsoares Bruno, testei todos os links e abriram sem problemas, você não tá conseguindo abrir nenhum deles? Pode testar com um DNS diferente?

**Comment by mmendesx** [comment]
Estou com o mesmo problema, os links não abrem aqui, testei todos.

**Comment by walmyrcarvalho** [comment]
@mathmendesdev obrigado pelo teste! Vou postar os links diretamente, sem os encurtadores!

**Comment by professorsoares** [comment]
> @professorsoares Bruno, testei todos os links e abriram sem problemas, você não tá conseguindo abrir nenhum deles? Pode testar com um DNS diferente?

Todos que são bit.do... não abrem nada...

**Comment by walmyrcarvalho** [comment]
@professorsoares Arrumamos isso [aqui](https://github.com/androiddevbr/materiais-de-estudo/pull/18), vou fechar a issue, OK? Obrigado pelo report!

Corrigido aqui: https://github.com/androiddevbr/materiais-de-estudo/pull/18
